### ISSUE TITLE
Bug. Removing Event Listeners throws consoler error

### ISSUE THREAD

**Issue by Nickztar** [rungwiroon/BlazorGoogleMaps#241]
After upgrading our blazor google maps we recieve the following issue when disposing our markers and event listeners. Any known cause for this.

`functionToInvoke: remove
args: `

`TypeError: obj[functionToInvoke] is not a function
    at Object.invoke (objectManager.js?q=3073f26f3d4442418c71a3ec35848679:600:55)
    at blazor.webassembly.js?q=framework_version:1:3337
    at new Promise (<anonymous>)
    at Object.beginInvokeJSFromDotNet (blazor.webassembly.js?q=framework_version:1:3311)
    at Object.Gt [as invokeJSFromDotNet] (blazor.webassembly.js?q=framework_version:1:62537)
    at Object.Ii (dotnet.7.0.2.tt5z2s8frk.js:5:71465)
    at _mono_wasm_invoke_js_blazor (dotnet.7.0.2.tt5z2s8frk.js:14:103886)
    at 00992bd6:0x1d4d8
    at 00992bd6:0x1c906
    at 00992bd6:0xdff6
    at 00992bd6:0xce95
    at 00992bd6:0x1a2195
    at 00992bd6:0x85bba
    at 00992bd6:0x86222
    at 00992bd6:0x882e1
    at 00992bd6:0x9bd1
    at Module._mono_wasm_invoke_method_ref (dotnet.7.0.2.tt5z2s8frk.js:14:123869)
    at _Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS (_Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS:26:5)
    at Object.endInvokeJSFromDotNet (blazor.webassembly.js?q=framework_version:1:45117)
    at blazor.webassembly.js?q=framework_version:1:3404`

**Comment by Nickztar** [comment]
After upgrading from 2.4.4 to 2.5.2 this occured.

**Comment by Nickztar** [comment]
Code does something like this:
![image](https://user-images.githubusercontent.com/54627464/215508275-8228269d-71d1-4cdf-9602-4295fb2aca99.png)

**Comment by valentasm1** [comment]
Problem with MapEventListener disposing with await _jsObjectRef.InvokeAsync("remove");. Basically removing event listeners.
I need to dig deeper to find how remove event listener smth like this
https://stackoverflow.com/questions/1544151/google-maps-api-v3-how-to-remove-an-event-listener

Possible reproduce with /map-control-events click on "RemoveEvent"
Will take a look on weekend.
Nothing very serious.
Does it crash app?

**Comment by Nickztar** [comment]
It does not crash, just does not dispose any elements.
I was unable to find where the change has been made. Since in 2.4.4 it works fine.

**Comment by Nickztar** [comment]
Im guessing that this is the way that we used to do it. Maybe we changes how we track the eventlisteners?

https://stackoverflow.com/a/17115579

**Comment by valentasm1** [comment]
There are a lot of "magic" in this library thats why it is not that simple.
Functions are invoked dynamically and some arguments or smth is missing. Thats why there is console error.

**Comment by valentasm1** [comment]
Reminder for myself. For some reasons our logic when we create event handler and then add to array so removing it dont work.
If i create that explicitly it work. So i think i just need create additional method. Sadly will take a look next weekend.

`
invokeWithReturnedObjectRef: async function (args) {
                //Dont work
                var promiseResult = await result;
                mapObjects[uuid] = promiseResult;
                google.maps.event.removeListener(promiseResult);

                //Works
                var listener1 = mapObjects["c656bfc9-03f4-49c3-838f-1a3f45af053d"].addListener('click', () => { });
                google.maps.event.removeListener(listener1);

                return uuid;
            },
`

**Comment by valentasm1** [comment]
Cha cha. In the morning while in the bed i was thinking "Hm i think that listener is serialized to string, that should be an issue". And it is. 
https://www.nuget.org/packages/BlazorGoogleMaps/2.5.3

**Comment by Nickztar** [comment]
Great stuff. Will check it out!
